export const UF_OPTIONS = [
  { value: "AC", label: "AC" },
  { value: "AL", label: "AL" },
  { value: "AP", label: "AP" },
  { value: "AM", label: "AM" },
  { value: "BA", label: "BA" },
  { value: "CE", label: "CE" },
  { value: "DF", label: "DF" },
  { value: "ES", label: "ES" },
  { value: "GO", label: "GO" },
  { value: "MA", label: "MA" },
  { value: "MT", label: "MT" },
  { value: "MS", label: "MS" },
  { value: "MG", label: "MG" },
  { value: "PA", label: "PA" },
  { value: "PB", label: "PB" },
  { value: "PR", label: "PR" },
  { value: "PE", label: "PE" },
  { value: "PI", label: "PI" },
  { value: "RJ", label: "RJ" },
  { value: "RN", label: "RN" },
  { value: "RS", label: "RS" },
  { value: "RO", label: "RO" },
  { value: "RR", label: "RR" },
  { value: "SC", label: "SC" },
  { value: "SP", label: "SP" },
  { value: "SE", label: "SE" },
  { value: "TO", label: "TO" },
];

export const PRODUCT_TYPE_OPTIONS = [
  { value: "EXTINGUISHER", label: "Extintor" },
  { value: "SERVICE", label: "Serviço" },
  { value: "CONSUMABLE", label: "Consumível" },
  { value: "ACCESSORY", label: "Acessório" },
  { value: "HOSE", label: "Mangueira" },
  { value: "DETECTOR", label: "Detector" },
  { value: "SPRINKLER", label: "Sprinkler" },
  { value: "CENTRAL", label: "Central" },
  { value: "LIGHTING", label: "Iluminação" },
  { value: "DOOR", label: "Porta" },
  { value: "HYDRANT", label: "Hidrante" },
];
